### ISSUE TITLE
Ability to not include the checkmark in the output

### ISSUE THREAD

**Issue by robinmitra** [k4m4/url-cli#1]
The checkmark (✔) makes it harder to pipe the output into other tools (e.g. `json` for formatting JSON). It would be useful if there was an option to hide the checkmark, or simply remove it altogether if it's not very useful (e.g. my prompt already displays the exit status of commands with a checkmark or a cross).

Let me know your thought. I can flush out a PR if needed.

**Comment by k4m4** [comment]
I agree; the checkmark makes it harder to pipe results. Maybe adding a `-h` flag to hide it would do the job. What do you think?

**Comment by robinmitra** [comment]
A flag would be my preferred solution too, but `-h` could be confusing since it's generally used for help. What about `--plain` or `-s` (for simple)? Or if you have any other options in mind?

**Comment by k4m4** [comment]
That's right, what am I talking about... I guess a `--plain`/`-p` flag would get the job done. Please feel free to send out a pull req.

**Comment by robinmitra** [comment]
Cool, if you can assign this to me, I can keep track and send the PR once I get back from holidays :)

**Comment by k4m4** [comment]
Implemented in [4ac0d8b](https://github.com/k4m4/url-cli/commit/4ac0d8b66071b2a26661da58354a8a090a48cbc5). Thanks again for the suggestion!
